build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "rabbitmq-c/0.8.0"
    CONAN_USERNAME: "bisect"
    CONAN_LOGIN_USERNAME: "promgamer"
    CONAN_CHANNEL: "stable"
    CONAN_UPLOAD: "https://api.bintray.com/conan/bisect/bisect"
    CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_LINK_RUNTIME: MD
  
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py

